### ISSUE TITLE
ToDo

### ISSUE THREAD

**Issue by Gvex95** [Gvex95/RedVoznje#1]
- [x] 1.namestiti glupave boje da rade
- [x] 2.namestiti cetriran teks, namestiti vremena sa pocetnom nulom i tackom
- [x] 3. Prosledjivanje izabranih opcija u novi activity
- [x] 4.dodati opcije,
    - [x] ceo red voznje
    - [x] prvi sledeci 

- [x] 5. obrnuti red voznje, u aktivitiju gde se prikazuje lista

- [ ] 6. U spineru ukloniti izabrani grad iz polaska i dodati dugme za zamenu

- [x] 7. Namestiti da se ne gasi notifikacija, tj izgled nakon sto switch uradim(moracu dodati polje u bazu color, i jedno polje
za vreme za notifikaciju kad uradi swap, tj kad updatetuje listu da se ne izgube ti podaci).
RESENO:
Dodat novi activity, koji se aktivira na onitemClicked kod liste, i gde se bira vreme, moze se izabrati i proizvoljno
To posle ograniciti na 0-60 minuta(mozda)?

- [ ] 8. Umesto u activitiju nek se to obavlja u dijalogu
- [ ] 9. Srediti kod!!!

- [ ] 10. Dodati notifikacije

- [ ] 11. Dodatni on on item long press, de ce iskociti kontext menu sa mestom polaska i svim mestima izmedju
- [ ] 12. Namestiti djacki bus
- [ ] 13. Poboljsati mutave boje da imaju neki znacaj
- [ ] 14. Dodaati baze za sva mesta
- [ ] 15. Dodati mozda aboutApp gde ce se objasniti useru sta i kako moze da klikne
- [ ] 16. Dodati dugme about, gde ce biti galerija i informacije o Dunavprevozu 
- [ ] 17. Namestiti da to sve izgleda lepo a ne ovako debilno(tema, boje, ikonica, generalni izgled)
